DIR=plots/210222_102836
mkdir -p $DIR
./controlPlots category 4 $DIR
./controlPlots nJets 5 $DIR
./controlPlots nBjets 3 $DIR
./controlPlots dilepPt 10 $DIR
./controlPlots dilepEta 12 $DIR
./controlPlots dilepPhi 10 $DIR
./controlPlots dilepMass 10 $DIR
./controlPlots missingEt 11 $DIR
./controlPlots missingPhi 10 $DIR
./controlPlots leadLepPt 10 $DIR
./controlPlots leadLepEta 10 $DIR
./controlPlots leadLepPhi 10 $DIR
./controlPlots sublLepPt 10 $DIR
./controlPlots sublLepEta 10 $DIR
./controlPlots sublLepPhi 10 $DIR
./controlPlots trailLepPt 10 $DIR
./controlPlots trailLepEta 10 $DIR
./controlPlots trailLepPhi 10 $DIR
./controlPlots firstJetPt 10 $DIR
./controlPlots firstJetEta 10 $DIR
./controlPlots firstJetPhi 10 $DIR
./controlPlots secondJetPt 10 $DIR
./controlPlots secondJetEta 10 $DIR
./controlPlots secondJetPhi 10 $DIR
./controlPlots thirdJetPt 10 $DIR
./controlPlots thirdJetEta 10 $DIR
./controlPlots thirdJetPhi 10 $DIR
./controlPlots fourthJetPt 10 $DIR
./controlPlots fourthJetEta 10 $DIR
./controlPlots fourthJetPhi 10 $DIR
./controlPlots ttzMass 8 $DIR
./controlPlots ttbarMass 8 $DIR
./controlPlots topPt 8 $DIR
./controlPlots deltaPhiTtbar 8 $DIR
./controlPlots deltaPhiTopZ 8 $DIR
./controlPlots deltaRapTtbar 8 $DIR
./controlPlots deltaRapTopZ 8 $DIR
