DIR=plots/210315_095935
mkdir -p $DIR
./controlPlots control_category3l 4 $DIR
./controlPlots control_category4l 6 $DIR
./controlPlots control_nJets 6 $DIR
./controlPlots control_nBjets 3 $DIR
./controlPlots control_dilepPt 10 $DIR
./controlPlots control_dilepEta 12 $DIR
./controlPlots control_dilepPhi 10 $DIR
./controlPlots control_dilepMass3l 10 $DIR
./controlPlots control_dilepMass4l 10 $DIR
./controlPlots control_missingEt 11 $DIR
./controlPlots control_missingPhi 10 $DIR
./controlPlots control_firstLepPt 10 $DIR
./controlPlots control_firstLepEta 10 $DIR
./controlPlots control_firstLepPhi 10 $DIR
./controlPlots control_secondLepPt 10 $DIR
./controlPlots control_secondLepEta 10 $DIR
./controlPlots control_secondLepPhi 10 $DIR
./controlPlots control_thirdLepPt 10 $DIR
./controlPlots control_thirdLepEta 10 $DIR
./controlPlots control_thirdLepPhi 10 $DIR
./controlPlots control_fourthLepPt 10 $DIR
./controlPlots control_fourthLepEta 10 $DIR
./controlPlots control_fourthLepPhi 10 $DIR
./controlPlots control_firstJetPt 10 $DIR
./controlPlots control_firstJetEta 10 $DIR
./controlPlots control_firstJetPhi 10 $DIR
./controlPlots control_secondJetPt 10 $DIR
./controlPlots control_secondJetEta 10 $DIR
./controlPlots control_secondJetPhi 10 $DIR
./controlPlots control_thirdJetPt 10 $DIR
./controlPlots control_thirdJetEta 10 $DIR
./controlPlots control_thirdJetPhi 10 $DIR
./controlPlots control_fourthJetPt 10 $DIR
./controlPlots control_fourthJetEta 10 $DIR
./controlPlots control_fourthJetPhi 10 $DIR
./controlPlots reco3l_lepTopMass 10 $DIR
./controlPlots reco3l_hadTopMass 10 $DIR
./controlPlots reco_zbosonPt 8 $DIR
./controlPlots reco3l_ttzMass 8 $DIR
./controlPlots reco3l_ttbarMass 8 $DIR
./controlPlots reco3l_topPt 8 $DIR
./controlPlots reco3l_deltaPhiTtbar 8 $DIR
./controlPlots reco3l_deltaPhiTopZ 8 $DIR
./controlPlots reco3l_deltaRapTtbar 8 $DIR
./controlPlots reco3l_deltaRapTopZ 8 $DIR
./controlPlots reco4l_topLeptonPt 8 $DIR
./controlPlots reco4l_topLeptonsMass 8 $DIR
./controlPlots reco4l_fourLeptonsMass 8 $DIR
./controlPlots reco4l_deltaPhiTopLeptons 8 $DIR
./controlPlots reco4l_deltaPhiTopLeptonZ 8 $DIR
./controlPlots reco4l_deltaRapTopLeptons 8 $DIR
./controlPlots reco4l_deltaRapTopLeptonZ 8 $DIR
